import type { DownloadItem, ValidationRow } from "../components";
import { benchmarkAssetPath } from "./assets";
import generated from "./generated/hindered-settling.json";
import generatedValidation from "./generated/hindered-settling-validation.json";
import type { PlotSource, PlotSpec, SeriesGroup } from "./types";

export type HinderedMetricId = "collapse" | "history";
export type HinderedCloudId = "n20" | "n40" | "n80" | "n120";

export const hinderedCloudSizes = [20, 40, 80, 120] as const;

const cloudColors: Record<HinderedCloudId, string> = {
  n20: "#5fb8ff",
  n40: "#f5b84b",
  n80: "#7bd88f",
  n120: "#ef6f6c"
};

function source(metric: string, file: string, kind: PlotSource["kind"]): PlotSource {
  return { kind, asset: { path: benchmarkAssetPath("hindered-settling", `plots/${metric}/${file}.json`) } };
}

function cloudGroup(metric: string, size: number, kind: PlotSource["kind"]): SeriesGroup {
  const id = `n${size}` as HinderedCloudId;
  return {
    id,
    label: `N = ${size}`,
    kind: "code",
    color: cloudColors[id],
    source: source(metric, id, kind),
    variantStrategy: { kind: "single-trace" }
  };
}

function referenceGroup(
  metric: string,
  id: string,
  label: string,
  kind: PlotSource["kind"],
  color: string
): SeriesGroup {
  return {
    id,
    label,
    kind: "reference",
    color,
    source: source(metric, id, kind),
    variantStrategy: { kind: "single-trace" }
  };
}

/**
 * Collapse plot. Plotted in the coordinates the exponent is fitted in — the axes
 * are logarithms, so the power law is the straight line through the origin and the
 * unbounded Rowe/RZ band is a pair of shallower lines.
 */
const collapseSpec: PlotSpec = {
  id: "hindered-collapse",
  title: "Power-law collapse",
  metric: "collapse",
  comparisonAxis: "code",
  seriesSelectorLabel: "Cloud size & references",
  seriesGroups: [
    ...hinderedCloudSizes.map(size => cloudGroup("collapse", size, "single-trace")),
    referenceGroup("collapse", "fit", `Fit, n = ${hinderedFitLabel()}`, "single-trace", "var(--fg1)"),
    referenceGroup("collapse", "rowe", "Unbounded Rowe/RZ band", "trace-array", "var(--fg3)")
  ],
  defaultSeriesGroupIds: ["n20", "n40", "n80", "n120", "fit", "rowe"],
  compareModes: ["overlay"],
  defaultCompareMode: "overlay",
  preserveSourceColorsWhenSingleGroup: false,
  axisLabels: { x: "ln(1 - phi)", y: "ln(U / u_t)" }
};

/**
 * Settling histories. Grouped by cloud size, with the two columns as variants, so
 * the plateau window and its steadiness are visible for each run that produced a
 * point on the collapse.
 */
const historySpec: PlotSpec = {
  id: "hindered-history",
  title: "Settling history",
  metric: "history",
  comparisonAxis: "code",
  seriesSelectorLabel: "Cloud size",
  seriesGroups: hinderedCloudSizes.map(size => cloudGroup("history", size, "trace-array")),
  defaultSeriesGroupIds: ["n20", "n40", "n80", "n120"],
  compareModes: ["overlay"],
  defaultCompareMode: "overlay",
  preserveSourceColorsWhenSingleGroup: false,
  axisLabels: { x: "Time t [-]", y: "U / u_t" }
};

export const hinderedPlotSpecs: Record<HinderedMetricId, PlotSpec> = {
  collapse: collapseSpec,
  history: historySpec
};

/**
 * Confinement panel. Cloud size is the one abscissa the two geometries share
 * without ambiguity: the clouds are identical, only the vessel differs.
 */
export const hinderedConfinementSpecs: Record<string, PlotSpec> = {
  hindrance: {
    id: "hindered-hindrance",
    title: "Plateau velocity by column",
    metric: "hindrance",
    comparisonAxis: "code",
    seriesSelectorLabel: "Column",
    seriesGroups: [
      {
        id: "confined",
        label: "6d column",
        kind: "code",
        color: "#5fb8ff",
        source: source("hindrance", "confined", "single-trace"),
        variantStrategy: { kind: "single-trace" }
      },
      {
        id: "wide",
        label: "12d column",
        kind: "code",
        color: "#ef6f6c",
        source: source("hindrance", "wide", "single-trace"),
        variantStrategy: { kind: "single-trace" }
      },
      referenceGroup("hindrance", "unhindered", "Single-particle u_t", "single-trace", "var(--fg3)")
    ],
    defaultSeriesGroupIds: ["confined", "wide", "unhindered"],
    compareModes: ["overlay"],
    defaultCompareMode: "overlay",
    preserveSourceColorsWhenSingleGroup: false,
    axisLabels: { x: "Particles in the cloud N", y: "U / u_t" }
  }
};

/* ---------------- Measured numbers ---------------- */

/**
 * Fitted exponent, plateau statistics and terminal-velocity references, all
 * generated by scripts/convert-hindered-settling-data.mjs from the curated run
 * tables. Never edit by hand — correct the source data and re-run the converter.
 */
export const hinderedFit = generated.fit;
export const hinderedWideSlope = generated.wideSlope;
export const hinderedRoweBand = generated.roweBand;
export const hinderedWindow = generated.window;
export const hinderedLadder = generated.ladder;
export const hinderedTerminal = generated.terminal;

export function hinderedFitLabel() {
  return generated.fit.n.toFixed(2);
}

export const hinderedTerminalByColumn = Object.fromEntries(
  generated.terminal.map(entry => [entry.column, entry])
) as Record<"6d" | "wide", (typeof generated.terminal)[number]>;

export interface HinderedLadderRow {
  n: number;
  seed: number;
  u: number;
  uStd: number;
  uOverUt: number;
  phiCloud: number;
  phiEnvelope: number;
  spread: number;
}

export const hinderedConfinedRows = generated.ladder.confined as HinderedLadderRow[];
export const hinderedWideRows = generated.ladder.wide as HinderedLadderRow[];

/** Swarm Reynolds number from the plateau velocity: Re = U d / nu, d = 1. */
export const hinderedViscosity = 0.0047;

export function swarmReynolds(u: number) {
  return u / hinderedViscosity;
}

/**
 * Swarm Reynolds range across the ladder, taken over the seed mean at each rung
 * rather than over individual runs — a single seed is not a rung of the ladder.
 */
export const hinderedReynoldsRange = (() => {
  const perRung = hinderedCloudSizes.map(size => {
    const rows = (generated.ladder.confined as HinderedLadderRow[]).filter(row => row.n === size);
    return swarmReynolds(rows.reduce((sum, row) => sum + row.u, 0) / rows.length);
  });
  return { min: Math.min(...perRung), max: Math.max(...perRung) };
})();

/* ---------------- Case definition ---------------- */

export interface HinderedParameterRow {
  symbol: string;
  quantity: string;
  value: string;
}

export const hinderedParameterRows: HinderedParameterRow[] = [
  { symbol: "d", quantity: "Sphere diameter", value: "1 (nondimensional)" },
  { symbol: "rho_p / rho_f", quantity: "Density ratio", value: "1.14" },
  { symbol: "nu", quantity: "Kinematic viscosity", value: "4.7e-3" },
  { symbol: "g", quantity: "Gravity", value: "1.0, along -z" },
  { symbol: "L x W x H", quantity: "Walled column", value: "6d x 6d x 24d" },
  { symbol: "L x W x H", quantity: "Control column", value: "12d x 12d x 24d" },
  { symbol: "N", quantity: "Particles in the cloud", value: "20, 40, 80, 120" },
  { symbol: "D/h", quantity: "Elements per diameter", value: "8" },
  { symbol: "mu_s, mu_d", quantity: "Contact friction", value: "0 (liquid contact)" },
  { symbol: "dt", quantity: "Time step", value: "5e-3, Crank-Nicolson" },
  { symbol: "t_end", quantity: "End time", value: "25 (5000 steps)" }
];

export interface HinderedRegimeRow {
  regime: string;
  geometry: string;
  law: string;
}

/** The three regimes this benchmark separates. */
export const hinderedRegimeRows: HinderedRegimeRow[] = [
  {
    regime: "Confined suspension",
    geometry: "Cloud fills the vessel cross-section",
    law: `Hindered, n = ${generated.fit.n.toFixed(2)} — measured here`
  },
  {
    regime: "Unbounded suspension",
    geometry: "Homogeneous, no vessel",
    law: `Hindered, n = ${generated.roweBand[0]}–${generated.roweBand[1]} (Rowe/RZ)`
  },
  {
    regime: "Finite cloud in a wide vessel",
    geometry: "Cloud occupies part of the cross-section",
    law: "Enhanced, U/u_t > 1 — no Richardson-Zaki form"
  }
];

/* ---------------- Validation ---------------- */

/**
 * Generated from the DNS validation datasheet by
 * scripts/convert-hindered-settling-data.mjs. Never edit by hand — correct the
 * datasheet and re-run the converter.
 */
export const hinderedValidationRows = generatedValidation.rows as ValidationRow[];
export const hinderedValidationSource = generatedValidation.source;

/* ---------------- References and downloads ---------------- */

export const hinderedReferences = [
  {
    id: "richardson-zaki-1954",
    text:
      "J. F. Richardson, W. N. Zaki; Sedimentation and fluidisation: Part I. Transactions of the Institution of Chemical Engineers 32, 35-53, 1954."
  },
  {
    id: "rowe-1987",
    text:
      "P. N. Rowe; A convenient empirical equation for estimation of the Richardson-Zaki exponent. Chemical Engineering Science 42 (11), 2795-2796, 1987. doi:10.1016/0009-2509(87)87035-5"
  }
];

const tableFiles: Array<{ name: string; description: string }> = [
  { name: "ladder_6d.csv", description: "Plateau statistics per run, 6d walled column" },
  { name: "ladder_wide.csv", description: "Plateau statistics per run, 12d control column" },
  { name: "terminal_velocity.csv", description: "Single-particle terminal velocity per column" }
];

const historyFiles = [
  { name: "history_6d_n20.dat", description: "Settling history, 6d column, N = 20" },
  { name: "history_6d_n40.dat", description: "Settling history, 6d column, N = 40" },
  { name: "history_6d_n80.dat", description: "Settling history, 6d column, N = 80" },
  { name: "history_6d_n120.dat", description: "Settling history, 6d column, N = 120" },
  { name: "history_wide_n40.dat", description: "Settling history, 12d column, N = 40" },
  { name: "history_wide_n120.dat", description: "Settling history, 12d column, N = 120" }
];

export const hinderedDownloads: DownloadItem[] = [
  {
    label: "hindered-settling.zip",
    href: benchmarkAssetPath("hindered-settling", "downloads/hindered-settling.zip"),
    description: "All run tables, settling histories and the validation datasheet"
  },
  {
    label: "dns_validation_datasheet.csv",
    href: benchmarkAssetPath("hindered-settling", "downloads/dns_validation_datasheet.csv"),
    description: "Complete DNS campaign claim ledger, one row per quantitative claim"
  },
  ...[...tableFiles, ...historyFiles].map(file => ({
    label: file.name,
    href: benchmarkAssetPath("hindered-settling", `downloads/${file.name}`),
    description: file.description
  }))
];

export const hinderedReferenceRows = [
  {
    fileType: "Run table",
    pattern: "ladder_6d.csv, ladder_wide.csv",
    columns: "N, seed, U, U_std, U_over_ut, phi_cloud, phi_envelope, spread"
  },
  {
    fileType: "Terminal velocity",
    pattern: "terminal_velocity.csv",
    columns: "column, cross_section, u_t, u_t_std"
  },
  {
    fileType: "Settling history",
    pattern: "history_*.dat",
    columns: "Time t [-], U / u_t"
  }
];
