import type { DownloadItem, ValidationRow } from "../components";
import { benchmarkAssetPath } from "./assets";
import generated from "./generated/numerical-viscometer.json";
import generatedValidation from "./generated/numerical-viscometer-validation.json";
import type { PlotSource, PlotSpec, SeriesGroup } from "./types";

export type ViscometerMetricId = "torque" | "viscosity";

function source(metric: string, file: string): PlotSource {
  return {
    kind: "single-trace",
    asset: { path: benchmarkAssetPath("numerical-viscometer", `plots/${metric}/${file}.json`) }
  };
}

function group(
  metric: string,
  id: string,
  label: string,
  kind: SeriesGroup["kind"],
  color: string
): SeriesGroup {
  return { id, label, kind, color, source: source(metric, id), variantStrategy: { kind: "single-trace" } };
}

/**
 * Torque history. The suspension run restarts from the empty instrument's own
 * dump, so both runs share one time axis and the seeding shows up as a step. The
 * y-range deliberately clips the start-up transient, which is two orders of
 * magnitude above the plateau and would flatten everything the plot is about.
 */
const torqueSpec: PlotSpec = {
  id: "viscometer-torque",
  title: "Torque history",
  metric: "torque",
  comparisonAxis: "code",
  seriesSelectorLabel: "Estimators & references",
  seriesGroups: [
    group("torque", "dna", "Volume-form estimator", "code", "#5fb8ff"),
    group("torque", "res", "Reaction estimator", "code", "#f5b84b"),
    group("torque", "res-corrected", "Reaction + transpose correction", "code", "#7bd88f"),
    group("torque", "exact", "Exact analytic torque", "reference", "var(--fg1)"),
    group("torque", "insertion", "Particles inserted", "reference", "var(--fg3)")
  ],
  defaultSeriesGroupIds: ["dna", "res", "res-corrected", "exact", "insertion"],
  compareModes: ["overlay"],
  defaultCompareMode: "overlay",
  preserveSourceColorsWhenSingleGroup: false,
  axisLabels: { x: "Time t [-]", y: "|T| [-]" },
  axisRanges: { x: [0, 250], y: [40, 110] }
};

/**
 * Relative viscosity against concentration, in the coordinates Einstein's law is
 * stated in. Two measured rungs, the composite target computed from the measured
 * concentration field, and the naive dilute line as a reference.
 */
const viscositySpec: PlotSpec = {
  id: "viscometer-viscosity",
  title: "Relative viscosity",
  metric: "viscosity",
  comparisonAxis: "code",
  seriesSelectorLabel: "Measurement & predictions",
  seriesGroups: [
    group("viscosity", "measured", "Measured, T(phi) / T(0)", "code", "#5fb8ff"),
    group("viscosity", "composite", "Composite-Einstein target", "reference", "var(--fg1)"),
    group("viscosity", "einstein", "Einstein, 1 + 2.5 phi", "reference", "var(--fg3)")
  ],
  defaultSeriesGroupIds: ["measured", "composite", "einstein"],
  compareModes: ["overlay"],
  defaultCompareMode: "overlay",
  preserveSourceColorsWhenSingleGroup: false,
  axisLabels: { x: "Particle volume fraction phi", y: "Relative viscosity eta" },
  axisRanges: { x: [0, 0.06], y: [0.99, 1.16] }
};

export const viscometerTorqueSpecs: Record<string, PlotSpec> = { torque: torqueSpec };
export const viscometerViscositySpecs: Record<string, PlotSpec> = { viscosity: viscositySpec };

/* ---------------- Measured numbers ---------------- */

/**
 * Instrument constants, plateau statistics and gate deviations, all generated by
 * scripts/convert-numerical-viscometer-data.mjs from the curated torque histories.
 * Never edit by hand — correct the source data and re-run the converter.
 */
export const viscometerInstrument = generated.instrument;
export const viscometerGates = generated.baselineGates;
export const viscometerProfile = generated.profile;

export interface ViscometerRung {
  run: string;
  label: string;
  phi: number;
  particles: number;
  window: number[];
  samples: number;
  torqueDna: number;
  torqueDnaPstd: number;
  torqueRes: number;
  torqueResPstd: number;
  gap: number;
  gapDeviation: number;
  scatter: number;
  drift: number;
  eta: number;
  etaPstd: number;
  etaCorrected: number;
  etaComposite: number;
  etaNaive: number;
  deviationComposite: number;
  deviationNaive: number;
}

export const viscometerRungs = generated.rungs as ViscometerRung[];

export const viscometerBaseline = viscometerRungs.find(rung => rung.run === "baseline")!;
export const viscometerEinstein = viscometerRungs.find(rung => rung.run === "einstein")!;

/** Signed percentage, as the page quotes deviations everywhere. */
export function percent(value: number, digits = 2) {
  return `${value >= 0 ? "+" : "−"}${Math.abs(value * 100).toFixed(digits)}%`;
}

/* ---------------- Case definition ---------------- */

export interface ViscometerParameterRow {
  symbol: string;
  quantity: string;
  value: string;
}

export const viscometerParameterRows: ViscometerParameterRow[] = [
  { symbol: "d", quantity: "Sphere diameter", value: "1 (nondimensional)" },
  { symbol: "r_i", quantity: "Rotating inner surface (bob)", value: String(viscometerInstrument.rInner) },
  { symbol: "r_a", quantity: "Static outer wall", value: String(viscometerInstrument.rOuter) },
  { symbol: "H", quantity: "Cell height, symmetry planes at both ends", value: String(viscometerInstrument.height) },
  { symbol: "Omega", quantity: "Angular velocity of the bob", value: String(viscometerInstrument.omega) },
  { symbol: "nu", quantity: "Kinematic viscosity", value: String(viscometerInstrument.nu) },
  { symbol: "rho_f", quantity: "Fluid density", value: String(viscometerInstrument.rho) },
  { symbol: "rho_p / rho_f", quantity: "Density ratio, gravity-free", value: "1.1" },
  { symbol: "Re_p", quantity: "Particle Reynolds number", value: "~0.5" },
  { symbol: "Ta", quantity: "Taylor number (subcritical)", value: "156" },
  { symbol: "D/h", quantity: "Elements per particle diameter", value: "8-9" },
  { symbol: "-", quantity: "Mesh", value: "18,800-hex O-grid, 108 subdomains" },
  { symbol: "dt", quantity: "Time step", value: "5e-2 (empty), 5e-3 (suspension)" }
];

export interface ViscometerGateRow {
  gate: string;
  reference: string;
  measured: string;
  deviation: string;
  tolerance: string;
}

/**
 * The four acceptance gates of the empty instrument. Every reference and every
 * measured value is the generated one, so the table cannot drift from the series.
 */
export const viscometerGateRows: ViscometerGateRow[] = [
  {
    gate: "Analytic torque",
    reference: viscometerInstrument.torqueExact.toFixed(4),
    measured: viscometerBaseline.torqueDna.toFixed(4),
    deviation: percent(viscometerGates.torque),
    tolerance: "+/- 3%"
  },
  {
    gate: "Azimuthal velocity profile",
    reference: "exact Couette",
    measured: `mean ${(viscometerProfile.mean_rel_error * 100).toFixed(2)}%, max ${(
      viscometerProfile.max_rel_error * 100
    ).toFixed(1)}%`,
    // An error magnitude, not a signed deviation, so it carries no sign.
    deviation: `${(viscometerProfile.mean_rel_error * 100).toFixed(2)}%`,
    tolerance: "pointwise agreement"
  },
  {
    gate: "Estimator concordance",
    reference: viscometerInstrument.transposeCorrection.toFixed(4),
    measured: viscometerBaseline.gap.toFixed(4),
    deviation: percent(viscometerBaseline.gapDeviation),
    tolerance: "+/- 3%"
  },
  {
    gate: "Corrected reaction estimator",
    reference: viscometerInstrument.torqueExact.toFixed(4),
    measured: viscometerGates.correctedTorque.toFixed(4),
    deviation: percent(viscometerGates.correctedDeviation, 4),
    tolerance: "+/- 3%"
  }
];

export interface ViscometerLadderRow {
  label: string;
  status: string;
  detail: string;
}

/** The concentration ladder as it stands: two rungs measured, two ahead. */
export const viscometerLadderRows: ViscometerLadderRow[] = [
  {
    label: "phi = 0",
    status: "Certified",
    detail: "Empty instrument against the exact analytic torque"
  },
  {
    label: "phi = 0.05",
    status: "Certified",
    detail: "Einstein gate, 225 spheres, against the composite-Einstein target"
  },
  { label: "phi = 0.10", status: "Running", detail: "Next rung of the concentration ladder" },
  {
    label: "phi = 0.20",
    status: "Planned",
    detail: "With a sub-grid lubrication comparison pair"
  }
];

/* ---------------- Validation ---------------- */

/**
 * Generated from the DNS validation datasheet by
 * scripts/convert-numerical-viscometer-data.mjs. Never edit by hand — correct the
 * datasheet and re-run the converter.
 */
export const viscometerValidationRows = generatedValidation.rows as ValidationRow[];
export const viscometerValidationSource = generatedValidation.source;

/* ---------------- References and downloads ---------------- */

export const viscometerReferences = [
  {
    id: "einstein-1906",
    text:
      "A. Einstein; Eine neue Bestimmung der Molekuldimensionen. Annalen der Physik 324 (2), 289-306, 1906. doi:10.1002/andp.19063240204"
  },
  {
    id: "einstein-1911",
    text:
      "A. Einstein; Berichtigung zu meiner Arbeit: Eine neue Bestimmung der Molekuldimensionen. Annalen der Physik 339 (3), 591-592, 1911. doi:10.1002/andp.19113390313"
  },
  {
    id: "taylor-1923",
    text:
      "G. I. Taylor; Stability of a viscous liquid contained between two rotating cylinders. Philosophical Transactions of the Royal Society A 223, 289-343, 1923. doi:10.1098/rsta.1923.0008"
  }
];

const dataFiles: Array<{ name: string; description: string }> = [
  { name: "torque_baseline.csv", description: "Torque history of the empty instrument, both estimators, every time step" },
  { name: "torque_einstein.csv", description: "Torque history of the phi = 0.05 suspension, both estimators, every time step" },
  { name: "rungs.csv", description: "Plateau window, cloud size and the two predictions per rung" },
  { name: "velocity_profile.csv", description: "Azimuthal velocity profile gate against the exact Couette solution" }
];

export const viscometerDownloads: DownloadItem[] = [
  {
    label: "numerical-viscometer.zip",
    href: benchmarkAssetPath("numerical-viscometer", "downloads/numerical-viscometer.zip"),
    description: "All torque histories, run tables and the validation datasheet"
  },
  {
    label: "dns_validation_datasheet.csv",
    href: benchmarkAssetPath("numerical-viscometer", "downloads/dns_validation_datasheet.csv"),
    description: "Complete DNS campaign claim ledger, one row per quantitative claim"
  },
  ...dataFiles.map(file => ({
    label: file.name,
    href: benchmarkAssetPath("numerical-viscometer", `downloads/${file.name}`),
    description: file.description
  }))
];

export const viscometerReferenceRows = [
  {
    fileType: "Torque history",
    pattern: "torque_baseline.csv, torque_einstein.csv",
    columns: "time, T_dna, T_res"
  },
  {
    fileType: "Run table",
    pattern: "rungs.csv",
    columns: "run, label, phi, particles, plateau_start, run_end, eta_composite, eta_naive"
  },
  {
    fileType: "Profile gate",
    pattern: "velocity_profile.csv",
    columns: "quantity, value"
  }
];
